error: pass the whole error_context, not just a data pointer
This makes it easier for "polymorphic" contexts to include
extra data _inside_ the struct, rather than relying on an
extra pointer indirection (which generally requires the
caller to allocate two variables).